/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f7xx_pav.h"


GPIO_ConfigTypeDef_t GPIO_Config;

void Gpio_Config()
{
	PAV_GPIO_ClockCmd(GPIOC, ENABLE);
	GPIO_Config.GPIO_PinNumber = GPIO_PIN_13;
	GPIO_Config.GPIO_PinMode = GPIO_MODE_INPUT;
	GPIO_Config.GPIO_PinPuPd = GPIO_PIN_PULLDOWN;
	GPIO_Config.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	PAV_GPIO_Init(GPIOC, &GPIO_Config);


	PAV_GPIO_ClockCmd(GPIOB, ENABLE);
	GPIO_Config.GPIO_PinNumber = GPIO_PIN_0 | GPIO_PIN_7 | GPIO_PIN_14;
	GPIO_Config.GPIO_PinMode = GPIO_MODE_OUTPUT;
	GPIO_Config.GPIO_PinPuPd = GPIO_PIN_NOPULL;
	GPIO_Config.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	GPIO_Config.GPIO_PinOutputType = GPIO_MODE_OUTPUT_PP;
	PAV_GPIO_Init(GPIOB, &GPIO_Config);
}

void delay(){
	for(uint32_t i = 0; i < 200000 ; i++);
}

int main(void)
{
	Gpio_Config();

    /* Loop forever */
	while(1)
	{
			if(PAV_GPIO_ReadPin(GPIOC, GPIO_PIN_13))
			{
				PAV_GPIO_TogglePin(GPIOB, GPIO_PIN_0 | GPIO_PIN_7 | GPIO_PIN_14);
				delay();
			}


	}
}
