/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f7xx_pav.h"


GPIO_ConfigTypeDef_t GPIO_Config;
int count = 0;

void Gpio_Config()
{
	PAV_GPIO_ClockCmd(GPIOC, ENABLE);
	GPIO_Config.GPIO_PinNumber = GPIO_PIN_13;
	GPIO_Config.GPIO_PinMode = GPIO_MODE_INPUT;
	GPIO_Config.GPIO_PinPuPd = GPIO_PIN_PULLDOWN;
	GPIO_Config.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	PAV_GPIO_Init(GPIOC, &GPIO_Config);

	PAV_GPIO_Config_Interrupt(GPIOC, GPIO_PIN_13, FALLING_EDGE);
	PAV_GPIO_Enable_Interrupt(GPIO_PIN_13, EXTI15_10_IRQn);
}

void delay(){
	for(uint32_t i = 0; i < 200000 ; i++);
}


int main(void)
{
	Gpio_Config();

    /* Loop forever */
	while(1)
	{
		count++;

		delay();
	}
}

/* This is the Interrupt Handler. Naming must be according to EXTI line */
void EXTI15_10_IRQHandler()
{
	PAV_GPIO_Clear_Interrupt(GPIO_PIN_13);

	// Whenever interrupt occurs reset the count variable
	count = 0;
}
