/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f7xx_pav_gpio.h"
#include "stm32f7xx_pav_usart.h"
#include <string.h>

USART_ConfigTypeDef_t	USART_Config;
GPIO_ConfigTypeDef_t    GPIO_Config;

uint8_t rx_buffer[20];
uint8_t tx_buffer[20];
uint8_t message[20];

uint8_t rx_index = 0;
uint8_t usart2RxBuffer[1];

int count = 0;

/* Simple Delay function for test purposes */
void delay(){
	for(uint32_t i = 0; i < 800000 ; i++);
}

void GPIO_Configure()
{
	GPIO_Config.GPIO_PinNumber = GPIO_PIN_0 | GPIO_PIN_7 | GPIO_PIN_14;
	GPIO_Config.GPIO_PinMode = GPIO_MODE_OUTPUT;
	GPIO_Config.GPIO_PinPuPd = GPIO_PIN_NOPULL;
	GPIO_Config.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	GPIO_Config.GPIO_PinOutputType = GPIO_MODE_OUTPUT_PP;
	PAV_GPIO_Init(GPIOB, &GPIO_Config);


	GPIO_Config.GPIO_PinMode = GPIO_MODE_AF;
	GPIO_Config.GPIO_PinNumber = GPIO_PIN_5;
	GPIO_Config.GPIO_PinOutputType = GPIO_MODE_OUTPUT_PP;
	GPIO_Config.GPIO_PinPuPd = GPIO_PIN_PULLUP;
	GPIO_Config.GPIO_PinSpeed = GPIO_SPEED_ULTRA;
	PAV_GPIO_Init(GPIOD, &GPIO_Config);
	PAV_GPIO_AF_Config(GPIOD, GPIO_PIN_5, GPIO_AF7_USART2);		// Configure Tx Pin as AF

	GPIO_Config.GPIO_PinNumber = GPIO_PIN_6;
	GPIO_Config.GPIO_PinPuPd = GPIO_PIN_PULLDOWN;
	PAV_GPIO_Init(GPIOD, &GPIO_Config);

	PAV_GPIO_AF_Config(GPIOD, GPIO_PIN_6, GPIO_AF7_USART2);		// Configure Rx Pin as AF

}

void Usart_Configure()
{
	USART_Config.BaudRate = USART_BAUD_9600;
	USART_Config.FlowControl = FLOW_CONTROL_NONE;
	USART_Config.Mode = USART_TX_RX;
	USART_Config.OverSampling = USART_OVERSAMPLING_16;
	USART_Config.Parity = USART_NO_PARITY;
	USART_Config.StopBit = USART_STOP_1B;
	USART_Config.SynchronousType = ASYNCHRONOUS;
	USART_Config.WordLength = USART_WORD_LENGTH_8BIT;

	PAV_USART_Init(USART2, &USART_Config);
}

int main(void)
{
	// This is necessary for systick interrupt and timeout events
	//Systick_Config();

	GPIO_Configure();

	Usart_Configure();

	PAV_USART_Start_Receive_IT(USART2);

    /* Loop forever */
	while(1)
	{

		count++;

	}
}


void USART2_IRQHandler()
{
	count = 0;
}
